language: python
install:
    - pip install .
    - pip install -r requirements.txt
    - git clone -b darshan-3.1.5 https://xgitlab.cels.anl.gov/darshan/darshan.git
    - (cd darshan/darshan-util && ./configure && make darshan-parser)
    - export "PATH=${PWD}/darshan/darshan-util:$PATH"
before_script:
    - export TZ=America/Los_Angeles
script: (cd tests && nosetests)
